name: Build
on: push

jobs:
  linter:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/action/setup
      - run: npm run test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: npm run build
      - name: Archive plugins
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: dist
